// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1UdvLtS-r7fkU2eqirlSiikQzgF_Io8',
    appId: '1:327607791924:web:c1e10252129b134c777561',
    messagingSenderId: '327607791924',
    projectId: 'space-news-core-fefc0',
    authDomain: 'space-news-core-fefc0.firebaseapp.com',
    storageBucket: 'space-news-core-fefc0.firebasestorage.app',
    measurementId: 'G-VGFX9NGDG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARe3eu-_Jmz_hRzLlZgqnxABYmtZyKfgY',
    appId: '1:327607791924:android:2b4a6a7535c8dead777561',
    messagingSenderId: '327607791924',
    projectId: 'space-news-core-fefc0',
    storageBucket: 'space-news-core-fefc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPn10XepfvtZ_64KeEPtAJLmAOKmtOxc',
    appId: '1:327607791924:ios:49c1b6391d169535777561',
    messagingSenderId: '327607791924',
    projectId: 'space-news-core-fefc0',
    storageBucket: 'space-news-core-fefc0.firebasestorage.app',
    iosBundleId: 'com.example.adventRemedPab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmPn10XepfvtZ_64KeEPtAJLmAOKmtOxc',
    appId: '1:327607791924:ios:49c1b6391d169535777561',
    messagingSenderId: '327607791924',
    projectId: 'space-news-core-fefc0',
    storageBucket: 'space-news-core-fefc0.firebasestorage.app',
    iosBundleId: 'com.example.adventRemedPab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1UdvLtS-r7fkU2eqirlSiikQzgF_Io8',
    appId: '1:327607791924:web:83ece9929fe55c82777561',
    messagingSenderId: '327607791924',
    projectId: 'space-news-core-fefc0',
    authDomain: 'space-news-core-fefc0.firebaseapp.com',
    storageBucket: 'space-news-core-fefc0.firebasestorage.app',
    measurementId: 'G-8R9YP029FB',
  );
}
